=== olyagil/epamTraining/task04/testdata/tourist-vouchers.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.training.by/tourist-vouchers"
        xmlns:tns="http://www.training.by/tourist-vouchers"
        elementFormDefault="qualified">

    <element name="tourist-vouchers">
        <complexType>
            <sequence>
                <element ref="tns:voucher"
                         minOccurs="2"
                         maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="voucher" type="tns:Voucher" abstract="true"/>
    <element name="city-break" type="tns:CityBreak"
             substitutionGroup="tns:voucher"/>
    <element name="rest" type="tns:Rest"
             substitutionGroup="tns:voucher"/>
    <element name="guided-tour" type="tns:GuidedTour"
             substitutionGroup="tns:voucher"/>
    <element name="pilgrimage-tour" type="tns:PilgrimageTour"
             substitutionGroup="tns:voucher"/>

    <complexType name="Voucher">
        <sequence>
            <element name="begin-data" type="dateTime"/>
            <element name="transport" type="tns:Transport"/>
            <element name="cost" type="tns:Cost"/>
            <element name="hotel-characteristic"
                     type="tns:HotelCharacteristic"/>
        </sequence>
        <attribute name="id" type="tns:Identification" use="required"/>
        <attribute name="country" type="string" use="required"/>
        <attribute name="number-nights" type="nonNegativeInteger" default="0"/>
    </complexType>


    <!--Тур выходного дня-->
    <complexType name="CityBreak">
        <complexContent>
            <extension base="tns:Voucher">
                <sequence>
                    <element name="shopping-centers-numbers">
                        <simpleType>
                            <restriction base="positiveInteger">
                                <maxInclusive value="15"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <!--Экскурсионный тур-->
    <complexType name="GuidedTour">
        <complexContent>
            <extension base="tns:Voucher">
                <sequence>
                    <element name="tour-guide" type="boolean"/>
                    <element name="excursions-number">
                        <simpleType>
                            <restriction base="positiveInteger">
                                <maxExclusive value="20"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <!--Отдых-->
    <complexType name="Rest">
        <complexContent>
            <extension base="tns:Voucher">
                <sequence>
                    <element name="resting" type="boolean"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <!--Паломничество-->
    <complexType name="PilgrimageTour">
        <complexContent>
            <extension base="tns:Voucher">
                <sequence>
                    <element name="bethel-number">
                        <simpleType>
                            <restriction base="positiveInteger">
                                <maxInclusive value="15"/>
                            </restriction>
                        </simpleType>
                    </element>
                </sequence>
            </extension>
        </complexContent>
    </complexType>


    <complexType name="Cost">
        <all>
            <element name="price" type="decimal"/>
            <element name="flight-include" type="boolean" default="false"/>
            <element name="hotel-include" type="boolean" default="true"/>
        </all>
        <attribute name="currency" type="tns:Currency" default="EUR"/>
    </complexType>

    <complexType name="HotelCharacteristic">
        <all>
            <element name="tv" type="boolean"/>
            <element name="fan" type="boolean"/>
            <element name="safe" type="boolean"/>
            <element name="wi-fi" type="boolean"/>
        </all>
        <attribute name="number-stars" type="positiveInteger" use="required"/>
        <attribute name="room-type" use="required">
            <simpleType>
                <restriction base="positiveInteger">
                    <maxInclusive value="5"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute name="meal-type" use="required" type="tns:Meal"/>
    </complexType>

    <simpleType name="Transport">
        <restriction base="string">
            <enumeration value="Bus"/>
            <enumeration value="Аir"/>
            <enumeration value="Car"/>
            <enumeration value="Railway"/>
            <enumeration value="Liner"/>
        </restriction>
    </simpleType>


    <simpleType name="Currency">
        <restriction base="string">
            <enumeration value="USD"/>
            <enumeration value="BYN"/>
            <enumeration value="EUR"/>
        </restriction>
    </simpleType>

    <simpleType name="Meal">
        <restriction base="string">
            <enumeration value="HB"/>
            <enumeration value="BB"/>
            <enumeration value="AL"/>
        </restriction>
    </simpleType>

    <simpleType name="Identification">
        <restriction base="string">
            <pattern value="([a-zA-Z])[a-zA-Z0-9]{7,19}"/>
        </restriction>
    </simpleType>
</schema>

=== olyagil/epamTraining/task04/data/tourist-vouchers.xml
<?xml version="1.0" encoding="UTF-8"?>

<tourist-vouchers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xmlns="http://www.training.by/tourist-vouchers"
                  xsi:schemaLocation="http://www.training.by/tourist-vouchers tourist-vouchers.xsd">


    <city-break id="qwerty2345678" country="Russia" number-nights="1">
        <begin-data>2019-03-20T15:30:00</begin-data>
        <transport>Railway</transport>
        <cost currency="USD">
            <price>100</price>
            <flight-include>true</flight-include>
            <hotel-include>true</hotel-include>
        </cost>
        <hotel-characteristic number-stars="3" meal-type="AL" room-type="3">
            <tv>true</tv>
            <fan>true</fan>
            <safe>false</safe>
            <wi-fi>true</wi-fi>
        </hotel-characteristic>
        <shopping-centers-numbers>10</shopping-centers-numbers>
    </city-break>

    <guided-tour id="qwerty12345" country="Турция" number-nights="10">
        <begin-data>2019-03-15T08:00:00</begin-data>
        <transport>Аir</transport>
        <cost currency="BYN">
            <price>1500</price>
            <flight-include>true</flight-include>
            <hotel-include>true</hotel-include>
        </cost>
        <hotel-characteristic number-stars="4" room-type="2" meal-type="AL">
            <tv>true</tv>
            <fan>true</fan>
            <safe>false</safe>
            <wi-fi>true</wi-fi>
        </hotel-characteristic>
        <tour-guide>true</tour-guide>
        <excursions-number>8</excursions-number>
    </guided-tour>

    <rest id="qwerty46989" country="Poland" number-nights="5">
        <begin-data>2019-03-30T12:16:00</begin-data>
        <transport>Railway</transport>
        <cost>
            <price>400</price>
            <flight-include>false</flight-include>
            <hotel-include>false</hotel-include>
        </cost>
        <hotel-characteristic number-stars="3" room-type="1" meal-type="HB">
            <tv>false</tv>
            <fan>true</fan>
            <safe>false</safe>
            <wi-fi>true</wi-fi>
        </hotel-characteristic>
        <resting>true</resting>
    </rest>
    <pilgrimage-tour id="qwerty79895" country="India">
        <begin-data>2018-12-25T14:25:00</begin-data>
        <transport>Аir</transport>
        <cost>
            <price>1000</price>
            <flight-include>true</flight-include>
            <hotel-include>true</hotel-include>
        </cost>
        <hotel-characteristic number-stars="3" room-type="1" meal-type="HB">
            <tv>false</tv>
            <fan>true</fan>
            <safe>true</safe>
            <wi-fi>false</wi-fi>
        </hotel-characteristic>
        <bethel-number>6</bethel-number>
    </pilgrimage-tour>

</tourist-vouchers>

=== olyagil/epamTraining/task04/testdata/tourist-vouchers.xml
<?xml version="1.0" encoding="UTF-8"?>

<tourist-vouchers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xmlns="http://www.training.by/tourist-vouchers"
                  xsi:schemaLocation="http://www.training.by/tourist-vouchers tourist-vouchers.xsd">


    <city-break id="qwerty2345678" country="Russia" number-nights="1">
        <begin-data>2019-03-20T15:30:00</begin-data>
        <transport>Railway</transport>
        <cost currency="USD">
            <price>100</price>
            <flight-include>true</flight-include>
            <hotel-include>true</hotel-include>
        </cost>
        <hotel-characteristic number-stars="3" meal-type="AL" room-type="3">
            <tv>true</tv>
            <fan>true</fan>
            <safe>false</safe>
            <wi-fi>true</wi-fi>
        </hotel-characteristic>
        <shopping-centers-numbers>10</shopping-centers-numbers>
    </city-break>


</tourist-vouchers>
